site_name: CS Tools
site_url: https://cs_tools.thoughtspot.com/
site_description: >-
  Tools created by the ThoughtSpot PS/CS organization to assist implementation and
  administration of your platform.

repo_name: thoughtspot/cs_tools
repo_url: https://github.com/thoughtspot/cs_tools
edit_uri: tree/docs/docs/

copyright: Copyright &copy; 2021 ThoughtSpot Inc. All Rights Reserved

theme:
  name: material
  logo: assets/logo_white.png
  features:
    - header.autohide
    - navigation.instant
    - navigation.tabs

  font:
    text: Optimo-Plain
    code: BB Roller Mono

  icon:
    repo: fontawesome/brands/github

  palette:
    - media: "(prefers-color-scheme: light)"
      primary: indigo
      accent: blue
      scheme: default
      # scheme: thoughtspot-light
      toggle:
        icon: material/lightbulb-outline
        name: switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: blue
      accent: indigo
      scheme: slate
      # scheme: thoughtspot-dark
      toggle:
        icon: material/lightbulb
        name: switch to light mode

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - mkdocs-cs_tools
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - assets/overrides/.icons
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tilde
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/thoughtspot/cs_tools
      name: find us on github

    - icon: fontawesome/solid/paper-plane
      link: mailto:ps-na@thoughtspot.com
      name: email the team

extra_css:
  - css/custom.css

extra_javascript:
  - js/konami.js

nav:
  - Home: index.md
  - Install: how-to/install-upgrade-cs-tools.md
  - Tools:
    - cs-tools/overview.md
    - Archiver: cs-tools/archiver/README.md
    - Extractor: cs-tools/extractor/README.md
    - Remote TQL: cs-tools/rtql/README.md
    - Remote tsload: cs-tools/rtsload/README.md
    - Security Sharing: cs-tools/security-sharing/README.md
    - User Management: cs-tools/user-management/README.md
    - Bulk Deleter: cs-tools/bulk-deleter/README.md
    - Searchable: cs-tools/searchable/README.md
    - 🔐 Scriptability: cs-tools/scriptability/README.md
    - 🔐 Sharding Recommender: cs-tools/sharding-recommender/README.md
  - Syncers:
    - "What's a Syncer?": syncer/what-is.md
    - The Protocol: syncer/protocol.md
    - ThoughtSpot Falcon: syncer/falcon.md
    - Snowflake: syncer/snowflake.md
    - Google BigQuery: syncer/bigquery.md
    # - Amazon Redshift: syncer/redshift.md
    - Google Sheets: syncer/gsheets.md
    # - Microsoft Excel: syncer/excel.md
    - CSV: syncer/csv.md
    - SQLite: syncer/sqlite.md
    # - JSON: syncer/json.md
  - How-to:
    - "Set up a Configuration File": how-to/configuration-file.md
    - "Scheduling Tools": how-to/scheduling-tool-commands.md
  - Changelog:
    - v1.3.0: changelog/1.3.0.md
    - v1.2.0: changelog/1.2.0.md
    - v1.1.0: changelog/1.1.0.md
    - v1.0.0: changelog/1.0.0.md
  - 🤓:
    - for-developers/contributing.md
    - for-developers/environment-setup.md
    # - for-developers/your-first-tool.md
    # - for-developers/project-architecture.md
    - for-developers/writing-documentation.md
    - "What is Markdown?": for-developers/what-is-markdown.md
    # - for-developers/FAQ.md
